// Generated by gencpp from file beginner_tutorials/scan_range.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H
#define BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : angle_min(0.0)
    , angle_max(0.0)
    , range_min(0.0)
    , range_max(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : angle_min(0.0)
    , angle_max(0.0)
    , range_min(0.0)
    , range_max(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_max_type;
  _angle_max_type angle_max;

   typedef float _range_min_type;
  _range_min_type range_min;

   typedef float _range_max_type;
  _range_max_type range_max;





  typedef boost::shared_ptr< ::beginner_tutorials::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::beginner_tutorials::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::beginner_tutorials::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::beginner_tutorials::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::scan_range_<ContainerAllocator1> & lhs, const ::beginner_tutorials::scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.angle_min == rhs.angle_min &&
    lhs.angle_max == rhs.angle_max &&
    lhs.range_min == rhs.range_min &&
    lhs.range_max == rhs.range_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::scan_range_<ContainerAllocator1> & lhs, const ::beginner_tutorials::scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::scan_range_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9231e3ac3c9a27ca200edbb34ea8ab8d";
  }

  static const char* value(const ::beginner_tutorials::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9231e3ac3c9a27caULL;
  static const uint64_t static_value2 = 0x200edbb34ea8ab8dULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/scan_range";
  }

  static const char* value(const ::beginner_tutorials::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max		 # maximum range value [m]\n"
;
  }

  static const char* value(const ::beginner_tutorials::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_min);
      stream.next(m.angle_max);
      stream.next(m.range_min);
      stream.next(m.range_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
    s << indent << "range_min: ";
    Printer<float>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<float>::stream(s, indent + "  ", v.range_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H
